// Auto generated by utensor-cli

#ifndef __MODELS_DNN6_2_H
#define __MODELS_DNN6_2_H
#include "uTensor/core/context.hpp"
void get_dnn6_2_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_DNN6_2_H